# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20170917_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('pricing', models.PositiveIntegerField(default=15, help_text='The cost of parking at the space for 5 minutes')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('size', models.PositiveIntegerField(choices=[(1, 'Motorcycle'), (2, 'Compact'), (3, 'Mid-sized'), (4, 'Large'), (5, 'Oversized')], help_text='This is the maximum vehicle size the parking space can support', verbose_name='Supported Automobile size')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='A list of features e.g. EV charging, shade, etc.', size=None)),
                ('address', models.CharField(help_text="Please store as: '<number> <street>' e.g. '123 Robertson'", max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('host', models.ForeignKey(help_text='The host that the parking space belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatingAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('repeating_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]), size=None)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingSpace')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('for_repeating', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Car')),
                ('fixed_availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parking.FixedAvailability')),
                ('repeating_availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parking.RepeatingAvailability')),
            ],
        ),
        migrations.AddField(
            model_name='fixedavailability',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingSpace'),
        ),
    ]
