# Generated by Django 2.1 on 2018-08-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid_out',
            field=models.BooleanField(default=False),
        ),
    ]
