# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedavailability',
            options={'verbose_name_plural': 'fixed availabilities'},
        ),
        migrations.AlterModelOptions(
            name='repeatingavailability',
            options={'verbose_name_plural': 'repeating availabilities'},
        ),
        migrations.AddField(
            model_name='repeatingavailability',
            name='pricing',
            field=models.PositiveIntegerField(default=15, help_text='The cost of parking at the space for 5 minutes'),
        ),
    ]
