# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import parking.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatingavailability',
            name='repeating_days',
            field=parking.fields.ChoiceArrayField(base_field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]), size=None),
        ),
    ]
