# Generated by Django 2.0.3 on 2018-04-22 08:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parking.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpaceRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=parking.fields.ChoiceArrayField(base_field=models.CharField(choices=[('EV Charging', 'EV Charging'), ('Lit', 'Lit'), ('Covered', 'Covered'), ('Guarded', 'Guarded')], max_length=50), blank=True, help_text='A list of features e.g. EV charging, Lit, etc.', size=None),
        ),
        migrations.AddField(
            model_name='parkingspacerating',
            name='parking_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingSpace'),
        ),
    ]
