# Generated by Django 2.1 on 2018-08-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20180805_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='host_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
