# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20170917_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='address',
            field=models.CharField(help_text="Please store as: '[number] [street]' e.g. '123 Robertson'", max_length=50),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'Motorcycle'), (2, 'Compact'), (3, 'Mid-sized'), (4, 'Large'), (5, 'Oversized')], max_length=50), help_text='A list of features e.g. EV charging, shade, etc.', size=None),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='size',
            field=models.PositiveIntegerField(choices=[(1, 'Motorcycle'), (2, 'Compact'), (3, 'Mid-sized'), (4, 'Large'), (5, 'Oversized')], help_text='This is the maximum vehicle size the parking space can support', verbose_name='Max supported automobile size'),
        ),
    ]
