# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import parking.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20170917_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatingavailability',
            name='repeating_days',
            field=parking.fields.ChoiceArrayField(base_field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=15), size=None),
        ),
    ]
