# Generated by Django 2.0.3 on 2018-04-23 19:14

from django.db import migrations, models
import parking.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20180422_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=parking.fields.ChoiceArrayField(base_field=models.CharField(choices=[('EV Charging', 'EV Charging'), ('Illuminated', 'Illuminated'), ('Covered', 'Covered'), ('Guarded', 'Guarded'), ('Surveillance', 'Surveillance')], max_length=50), blank=True, help_text='A list of features e.g. EV charging, Illuminated, etc.', size=None),
        ),
    ]
