# Generated by Django 2.0.7 on 2018-07-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20180423_1214'),
    ]

    operations = [
        migrations.RenameField('ParkingSpace', 'description', 'instructions'),
    ]
