# Generated by Django 2.1 on 2018-08-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_reservation_host_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='host_income',
        ),
    ]
