# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20170917_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(1, 'EV Charging'), (2, 'Lit'), (3, 'Covered'), (4, 'Guarded')]), help_text='A list of features e.g. EV charging, shade, etc.', size=None),
        ),
    ]
