# Generated by Django 2.0.7 on 2018-07-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20180717_0143'),
    ]

    operations = [
        migrations.RenameField('ParkingSpace', 'address', 'name'),
    ]
