# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20170917_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EV Charging', 'EV Charging'), ('Lit', 'Lit'), ('Covered', 'Covered'), ('Guarded', 'Guarded')], max_length=50), help_text='A list of features e.g. EV charging, shade, etc.', size=None),
        ),
    ]
