# Generated by Django 2.1 on 2018-08-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20180805_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='host_income',
            field=models.PositiveIntegerField(),
        ),
    ]
