# Generated by Django 2.0.7 on 2018-07-17 05:03

from django.db import migrations, models
import parking.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20180717_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=parking.fields.ChoiceArrayField(base_field=models.IntegerField(choices=[(1, 'EV Charging'), (2, 'Illuminated'), (3, 'Covered'), (4, 'Guarded'), (5, 'Surveillance'), (6, 'Gated')]), blank=True, help_text='A list of features e.g. EV charging, Illuminated, etc.', size=None),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='instructions',
            field=models.CharField(blank=True, help_text='Any instructions that will help customers find the parking spot', max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='name',
            field=models.CharField(help_text="e.g. '123 Robertson' or 'Sam's Diner'", max_length=50),
        ),
    ]
