# Generated by Django 2.1 on 2018-08-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20180806_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatingavailability',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
