# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20170917_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fixed_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parking.FixedAvailability'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='repeating_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parking.RepeatingAvailability'),
        ),
    ]
