# Generated by Django 2.0.7 on 2018-07-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20180717_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='legal_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business')], default='Residential', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='physical_type',
            field=models.CharField(choices=[('Driveway', 'Driveway'), ('Garage', 'Garage'), ('Lot', 'Parking Lot'), ('Structure', 'Parking Structure'), ('Unpaved', 'Unpaved Lot')], default='Driveway', max_length=50),
            preserve_default=False,
        ),
    ]
