# Generated by Django 2.1 on 2018-08-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20180807_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='car',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='available_spaces',
            field=models.PositiveIntegerField(default=1, help_text="NOTE: Each individual parking space should be positioned such that each vehicle can arrive and leave independent of other vehicles currently parked at that location. If this is not possible, please enter '1' as the number of spaces available.", verbose_name='Number of spaces available'),
        ),
    ]
