# Generated by Django 2.0.7 on 2018-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20180717_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
