# Generated by Django 2.1 on 2018-08-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180811_1543'),
        ('parking', '0009_auto_20180809_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Address'),
        ),
    ]
