# Generated by Django 2.1 on 2018-08-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_parkingspace_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedavailability',
            name='pricing',
            field=models.PositiveIntegerField(default=100, help_text='The cost (in U.S. cents) of parking at the space for 1 hour'),
        ),
    ]
