# Generated by Django 2.1 on 2018-08-11 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_auto_20180811_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Address'),
        ),
    ]
