# Generated by Django 2.1 on 2018-08-17 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_auto_20180816_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 16, 23, 23, 6, 56720)),
            preserve_default=False,
        ),
    ]
