# Generated by Django 2.1 on 2018-08-17 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_parkingspace_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 17, 6, 40, 33, 711926, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repeatingavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 17, 6, 40, 42, 967471, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
