# Generated by Django 2.1 on 2018-08-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_auto_20180818_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
    ]
