# Generated by Django 2.1 on 2018-09-02 07:16

from django.db import migrations, models
import django.db.models.deletion
import parking.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0018_auto_20180818_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.ParkingSpace'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='features',
            field=parking.fields.ChoiceArrayField(base_field=models.CharField(choices=[('EV Charging', 'EV Charging'), ('Illuminated', 'Illuminated'), ('Covered', 'Covered'), ('Guarded', 'Guarded'), ('Surveillance', 'Surveillance'), ('Gated', 'Gated')], max_length=50), blank=True, help_text='A list of features e.g. EV charging, Illuminated, etc.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='host',
            field=models.ForeignKey(help_text='The host that the parking space belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Host'),
        ),
        migrations.AlterField(
            model_name='repeatingavailability',
            name='pricing',
            field=models.PositiveIntegerField(default=100, help_text='The cost (in U.S. cents) of parking at the space for 1 hour'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Vehicle'),
        ),
    ]
