# Generated by Django 2.1 on 2018-09-07 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_auto_20180902_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fixed_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.FixedAvailability'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parking.ParkingSpace'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='repeating_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.RepeatingAvailability'),
        ),
    ]
