# Generated by Django 2.1 on 2018-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0020_auto_20180906_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='deleted',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
