# Generated by Django 2.1 on 2019-02-10 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0021_auto_20180906_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='repeatingavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repeatingavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
