# Generated by Django 2.1 on 2019-02-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_auto_20190209_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='instructions',
            field=models.CharField(blank=True, help_text='Any instructions that will help customers find the parking spot', max_length=1000, null=True),
        ),
    ]
