# Generated by Django 2.1 on 2018-08-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180805_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
