# Generated by Django 2.0.3 on 2018-04-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170917_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='host',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
