# Generated by Django 2.0.3 on 2018-04-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180422_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='size',
            field=models.PositiveIntegerField(choices=[(1, 'Motorcycle'), (2, 'Compact'), (3, 'Mid-sized'), (4, 'Large'), (5, 'Oversized')], default=3),
            preserve_default=False,
        ),
    ]
