# Generated by Django 2.1 on 2018-08-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20180809_1815'),
        ('accounts', '0004_auto_20180805_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Vehicle',
        ),
    ]
