# Generated by Django 2.0.7 on 2018-07-23 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_car_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_since',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 7, 23, 23, 0, 9, 4981)),
            preserve_default=False,
        ),
    ]
