# Generated by Django 2.1 on 2018-08-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_host_host_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(default='hl', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
