# Generated by Django 2.1 on 2018-08-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180810_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Address'),
        ),
    ]
