# Generated by Django 2.1 on 2018-08-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180810_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
