# Generated by Django 2.1 on 2018-08-17 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180811_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 17, 6, 37, 59, 703865, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
